name: Frontend CI

on: 
    push:
        paths:
            - 'frontend/retail-management-next/**'
    
    pull_request:
        paths:
            - 'frontend/retail-management-next/**'

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: install dependencies
              run: |
                  cd frontend/retail-management-next
                  npm ci

            - name: Build
              run: |
                  cd frontend/retail-management-next
                  npm run build

