name: Frontend CI

on: 
    push:
        paths:
            - '**'
    
    pull_request:
        paths:
            - '**'

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: install dependencies
              run: npm ci

            - name: Build
              run:  npm run build

